baseURL = "https://rossm.tech"
languageCode = "en-au"
title = "Ross McDermott"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:month/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    since = 2018
    author = "Ross McDermott"                           # Author's name
    avatar = "/images/me/avatar.jpeg"           # Author's avatar
    subtitle = "Ross McDermott | Cloud Specialist"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">license</a>'

[params.social]
    GitHub = "ross-mcdermott"
    Email   = "ross.mcdermott@outlook.com"
    LinkedIn = "rossrmcdermottau"
